#!/usr/bin/env bash

main() {
  mkdir -p /workspace/buildkitd
  exec sudo /usr/bin/buildkitd --debug  --config ./buildkitd.toml --group gitpod
}

if [ -z ${GITPOD_WORKSPACE_ID+x} ]; then
  main
elif [ -z ${FORCE_RUN_BUILDKITD+x} ]; then
  main
else
  echo "error: You must be inside an Gitpod workspace to continue. To force it, set FORCE_RUN_BUILDKITD variable"
  echo "error: to any value."
  exit 1
fi