# Sync all the iamges that are tagged using date time stamp
# format +%Y-%m-%d-%H-%M-%S e.g. 2022-02-22-10-10-54.
# Use simple regex for readability. Since we tag all images with year
# We use a regex rule: Any tag that starts with '20'.
"ghcr.io/gitpodify/gitpodified-workspace-images/dazzle-build-artifact":
  images-by-tag-regex:
    base: "20.*"
    c: "20.*"
    clojure: "20.*"
    elixir: "20.*"
    full: "20.*"
    vnc: "20.*"
    go: "20.*"
    nix: "20.*"
    node: "20.*"
    node-lts: "20.*"
    python: "20.*"
    python-3.7: "20.*"
    python-3.8: "20.*"
    python-3.9: "20.*"
    python-3.10: "20.*"
    ruby-2: "20.*"
    ruby-3: "20.*"
    rust: "20.*"
    dotnet: "20.*"
    postgresql: "20.*"
    mysql: "20.*"
    mongodb: "20.*"
    java-11: "20.*"
    java-17: "20.*"
    yugabytedb: "20.*"
