# https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md#yaml-file-content-used-source-for---src-yaml
localhost:5000:
  recaptime-dev:
    gp-ws-images-build-artifacts:
    - base
    - c
    - clojure
    - full
    - full-vnc
    - go
    - node
    - node-lts
    - python
    - ruby-2
    - ruby-3
    - rust
    - dotnet-vnc
    - postgresql
    - mysql
    - mongodb
    - java-11
    - java-17
    - yugabytedb
