# https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md#yaml-file-content-used-source-for---src-yaml
localhost:5000:
  recaptime-dev:
    gp-ws-images-build-artifacts:
    - base
    - c
    - clojure
    - elixir
    - full
    - vnc
    - go
    - nix
    - node
    - node-lts
    - python
    - python-3.7
    - python-3.8
    - python-3.9
    - python-3.10
    - ruby-2
    - ruby-3
    - rust
    - dotnet
    - postgres
    - mysql
    - mongodb
    - java-11
    - java-17
    - yugabytedb
