image:
  file: .gitpod.Dockerfile
  context: .

tasks:
    # TODO: Implement GitHub Container Registry-as-artifact store soon.
  - name: Workspace Setup + Monitoring
    init: |
      direnv allow
      git remote add upstream https://github.com/gitpod-io/workspace-images
    before: |
      direnv allow; direnv reload
      git fetch --all
      gp sync-done docker-cli-login
    command: htop
  - name: Docker CLI Auth + Buildkitd
    before: |
      gp sync-await docker-cli-login
      direnv reload
      ./devkit/docker-cli-login
      ./devkit/bin/skopeo-auth-ghcr
    command: ./devkit/gp-buildkit
  - name: Main Hub
    command: |
      ./devkit/local-registry

ports:
  - port: 5000
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck
    - redhat.vscode-yaml
    - eamodio.gitlens
    - gitlab.gitlab-workflow
    - davidanson.vscode-markdownlint
    - vivaxy.vscode-conventional-commits
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
