image: quay.io/gitpodified-workspace-images/full:latest

tasks:
  - name: Trust envrc file
    init: direnv allow
    before: |
      direnv allow; direnv reload
      gp sync-done docker-cli-login
  - name: Authenicate with the Docker CLI
    before: |
      gp sync-await docker-cli-login
      direnv reload
      RHQCR_USERBOT_USERNAME=$RHQCR_USERNAME RHQCR_USERBOT_PASSWORD=$RHQCR_PASSWORD ./.gitlab/ci/scripts/docker-cli-login
    command: docker

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck
    - redhat.vscode-yaml
    - eamodio.gitlens
    - gitlab.gitlab-workflow
    - davidanson.vscode-markdownlint

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
