.docker-build-dazzle:
    stage: build
    script:
      - |
        echo "===== Debugging section ====="
        env | grep TAG_NAME
        env | grep CONTEXT
      - ./.gitlab/ci/scripts/wait-docker-tcp
      - ./.gitlab/ci/scripts/selective-build-handler "$CONTEXT_DIR/$CONTEXT_DOCKERFILE" "$TAG_NAME"
    variables:
      BASE_TAG_NAME: quay.io/gitpodified-workspace-images/
      # Assume the defaults unless otherwise stated.
      CONTEXT_DOCKERFILE: Dockerfile
      # Needed for readiness checks via our script.
      DIND_RUN_HEALTHCHECK_BEFORE_BUILD: "true"
      BUILD_MODE: dazzle

.docker-build-plain:
    extends:
      - .docker-build-dazzle
    stage: build
    script:
      - |
        echo "===== Debugging section ====="
        env | grep TAG_NAME
        env | grep CONTEXT
      - ./.gitlab/ci/scripts/wait-docker-tcp
      - set -x && ./.gitlab/ci/scripts/selective-build-handler $CONTEXT_DIR/$CONTEXT_DOCKERFILE $TAG_NAME ${CUSTOM_TAG:-"latest"}
    timeout: 2h 30m
    variables:
      BASE_TAG_NAME: quay.io/gitpodified-workspace-images
      # Assume the defaults unless otherwise stated.
      CONTEXT_DOCKERFILE: Dockerfile
      DIND_RUN_HEALTHCHECK_BEFORE_BUILD: "true"
      DEBUG: "true"
      BUILD_MODE: docker

ws-base:build:
    needs:
      - ws-base:lint
    extends:
      - .docker-build-plain
    variables:
      TAG_NAME: $BASE_TAG_NAME/base
      CONTEXT_DIR: base
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - when: on_success

ws-full:build:
    needs:
      - ws-full:lint
      - ws-base:build
    extends:
      - .docker-build-plain
    variables:
      TAG_NAME: $BASE_TAG_NAME/full
      CONTEXT_DIR: full
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - full/dockerfile
          - full/tests/*.yml
          - full/nginx/nginx.conf
          - full/apache2/apache2.conf
          - full/apache2/envvars
          - devkit/bin/gp-devenv
          - full/zshrc.d/*.zshrc
          - base/base.zshrc
      - when: manual

ws-vnc:build:
    needs:
      - ws-full:build
      - ws-vnc:lint
    extends:
      - .docker-build-plain
    variables:
      TAG_NAME: $BASE_TAG_NAME/vnc
      CONTEXT_DIR: vnc
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - vnc/Dockerfile
          - vnc/*.sh
          - vnc/*.html

ws-gecko:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-gecko:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/gecko
    CONTENT_DIR: gecko
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - gecko/Dockerfile

ws-mdbook:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-mdbook:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/mdbook
    CONTENT_DIR: mdbook
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - mdbook/Dockerfile

ws-wasm:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-wasm:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/mdbook
    CONTENT_DIR: mdbook
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - wasm/Dockerfile

ws-mongodb:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-mongodb:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/mongodb
    CONTENT_DIR: mongodb
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - mongodb/Dockerfile

ws-postgres:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-postgres:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/postgres
    CONTENT_DIR: postgres
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - postgres/Dockerfile

ws-mysql:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-mysql:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/mysql
    CONTENT_DIR: mysql
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - mysql/Dockerfile

ws-dart:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-dart:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/dart
    CONTENT_DIR: dart
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - dart/Dockerfile

ws-flutter:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-dart:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/flutter
    CONTENT_DIR: flutter
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - flutter/Dockerfile

ws-dotnet:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-dotnet:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/dotnet
    CONTENT_DIR: dotnet
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - dotnet/Dockerfile

ws-dotnet-vnc:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-dotnet:build
    - ws-dotnet-vnc:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/dotnet
    CONTENT_DIR: dotnet
    CONTEXT_DOCKERFILE: vnc.Dockerfile
    CUSTOM_TAG: vnc
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - dotnet/vnc.Dockerfile

ws-dotnet-lts:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-dotnet:build
    - ws-dotnet-lts:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/dotnet
    CONTENT_DIR: dotnet
    CUSTOM_TAG: lts
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - dotnet/lts.Dockerfile

ws-dotnet-lts-vnc:build:
  extends:
      - .docker-build-plain
  needs:
    - ws-full:build
    - ws-vnc:build
    - ws-dotnet-lts:build
    - ws-dotnet-lts-vnc:lint
  variables:
    TAG_NAME: $BASE_TAG_NAME/dotnet
    CONTENT_DIR: dotnet
    CUSTOM_TAG: lts-vnc
  rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
        variables:
          TRIGGER_REBUILD: "true"
      - changes:
          - .trigger-build
          - dotnet/lts-vnc.Dockerfile
