#!/usr/bin/env bash

echo "===== Installing packages ====="
curl -sL https://deb.nodesource.com/setup_14.x | bash -
./base/install-packages zip \
        unzip \
        htop \
        jq \
        less \
        sudo \
        time \
        emacs-nox \
        vim \
        multitail \
        lsof \
        ssl-cert \
        fish \
        zsh \
        uuid \
        uuid-runtime \
        python3 \
        python3-pip \
        git \
        git-lfs \
        ca-certificates
echo "===== Installing shfm from GitHub releases ====="
curl -sSL https://github.com/mvdan/sh/releases/download/v3.4.2/shfmt_v3.4.2_linux_amd64 -o shfmt
mv shfmt /usr/local/bin/shfmt && sudo chmod +x /usr/local/bin/shfmt
echo "===== Installing Hadolint from GitHub releases ====="
wget https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 -O /usr/local/bin/hadolint && chmod +x /usr/local/bin/hadolint
echo "===== Installing Doppler CLI ====="
curl -fsSL https://cli.doppler.com/install.sh | sh
echo "===== Authenicating Docker CLI against container registries ====="
./.gitlab/ci/scripts/run-in-doppler $PWD/.gitlab/ci/scripts/docker-cli-login