#!/bin/bash
set -euo pipefail

REPO=${REPO:-"dazzle-cache.recaptime-dev.internal:5000/recaptime-dev/gp-ws-images-build-artifacts"}

REPO_ROOT="$(git rev-parse --show-toplevel)"

echo "====> Building chunks..."
### COPIED FROM THE MAIN dazzle-up.sh FILE - START ###
# First, build chunks without hashes
dazzle --addr tcp://buildkitd.recaptime-dev.internal:12340 build $REPO -v --chunked-without-hash
# Second, build again, but with hashes
dazzle --addr tcp://buildkitd.recaptime-dev.internal:12340 build $REPO -v
# Third, create combinations of chunks
dazzle --addr tcp://buildkitd.recaptime-dev.internal:12340 combine $REPO --all -v
### COPIED FROM THE MAIN dazzle-up.sh FILE - END ###

# Authenicate against GHCR via Skopeo and then mirror stuff to there
./.gitlab/ci/scripts/run-in-doppler "$REPO_ROOT/skopeo-auth-ghcr"
echo "===> Synchorizing build artifacts to GHCR..."
"$REPO_ROOT/devkit/bin/skopeo-gp-cache-sync"
