#!/usr/bin/env bash

if [[ "$RHQCR_SERVICE_ACCOUNT_USERNAME" == "" || "$RHQCR_SERVICE_ACCOUNT_PASSWORD" == "" ]]; then
  echo "warning: Missing login info for quay.io registry!"
else
  docker login -u "$RHQCR_USERBOT_USERNAME" -p "$RHQCR_SERVICE_ACCOUNT_PASSWORD" quay.io
fi
