#!/usr/bin/env bash

if [[ $1 == "" ]]; then
  echo "Requires 1 arg to run the linter!"
fi

BASEDIR=$(git rev-parse --show-toplevel)
DIR=$(dirname "$BASEDIR/$1")

echo "Target directory: $DIR"; sleep 5
echo "============================== SHELLCHECK RESULTS =============================="
./.gitlab/ci/scripts/lint-scripts "$DIR" || export CHECK_FAILED_SC=$?
echo "============================== SHELLCHECK RESULTS =============================="
echo
echo "============================== HADOLINT RESULTS =============================="
./.gitlab/ci/scripts/lint-dockerfile "$1" || export CHECK_FAILED_HL=$?
echo "============================== HADOLINT RESULTS =============================="

if [[ $CHECK_FAILED_SC != "0" || $CHECK_FAILED_HL != "0" ]]; then
  echo "error: Either linter checks had been failed. Please fix the issues above in order to go green."
  echo "error: Failing lint step with warning..."
  exit 1
fi