#!/usr/bin/env bash

if [[ $1 == "" ]]; then
  echo "Usage: $0 DIRECTORY"
  echo "Script to recurisively lint scripts with ShellCheck."
  exit 2
fi

# added an ! -path directive to avoid scanning Dockerfiles also
find "$1" ! -path '*/*.Dockerfile' ! -type f -print0 -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; | xargs --null shellcheck
