#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 IMAGE_TAG [...]"
  echo "Atleast one arg is required to recursively push Docker images."
  exit 2
fi

for imageTag in "$@"; do
  if ! docker push "$imageTag"; then
    echo "error: $imageTag failed to push, aborting..."
    exit 1
  else
    echo "info: $imageTag successfully pushed, sleeping for 5 seconds..."
    sleep 5
  fi
done