name: Sync to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to apply to the image'
        required: true

jobs:
  # Sync container images between the GCP Artifact registry and Docker Hub
  # To implement manual approvals, the workflow uses an Environment.
  promote:
    runs-on: ubuntu-latest
    environment: "production"
    env:
      SOURCE_IMAGE_REGISTRY: ghcr.io
      DEST_IMAGE_REGISTRY: quay.io

    steps:
      - name: 📥 Checkout workspace-images
        uses: actions/checkout@v2
        with:
          repository: gitpodify/gitpodified-workspace-images

      - name: 🔆 Install skopeo
        run: |
          . /etc/os-release
          # Update ca-certificates to avoid issues with letsencrypt SSL certificates
          sudo apt update && sudo apt --only-upgrade install ca-certificates -y
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
          sudo apt update && sudo apt install -y skopeo

      - name: ✍🏽 Configuring Skopeo for Google Artifact Registry
        run: |

          echo "===> Authenicating against GHCR"
          sudo skopeo login -u RecapTimeBot --password=${{ secrets.GHCR_SERVICE_ACCOUNT_PASSWORD }} https://${{env.SOURCE_IMAGE_REGISTRY}}
          echo
          sleep 3

          echo "===> Authenicating against RHQCR"
          sudo skopeo login -u ${{ secrets.RHQCR_SERVICE_ACCOUNT_USERNAME }} --password=${{secrets.RHQCR_SERVICE_ACCOUNT_PASSWORD}} ${{env.DEST_IMAGE_REGISTRY}}

      - name: 🐳 Sync images to Docker Hub
        env:
          IMAGE_TAG: ${{github.events.input.tag}}
        run: |
          sudo skopeo sync \
            --src docker \
            --dest docker \
            ${{env.SOURCE_IMAGE_REGISTRY}}/gitpodify/gitpodified-workspace-images/dazzle-build-artifacts:$IMAGE_TAG ${{env.DEST_IMAGE_REGISTRY}}/gitpodified-workspace-images
