name: Publish latest images to RHQCR + Cloudsmith

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 10 * * TUE"

env:
  RHQCR_REGISTRY: quay.io
  RHQCR_NAMESPACE: gitpodified-workspace-images
  GHCR_REGISTRY: ghcr.io
  GHCR_NAMESPACE: gitpodify/gitpodified-workspace-image/dazzle-build-artifact
  CLOUDSMITH_REGISTRY: docker.cloudsmith.io
  CLOUDSMITH_NAMESPACE: gitpodify/gitpodified-workspace-image

jobs:
  # Sync the 'latest' tag from GAR to Docker Hub
  #
  # From your GitHub repo clock Settings. In the left menu, click Environments.
  # Click New environment, set the name production, and click Configure environment.
  # Check the "Required reviewers" box and enter at least one user or team name.
  promote-latest:
    runs-on: ubuntu-latest
    environment:
      name: "release-ci/retag-to-latest"
      url: https://quay.io/gitpodified-workspace-images
    permissions:
      contents: "read"

    steps:
      - name: 📥 Checkout workspace-images
        uses: actions/checkout@v3
        with:
          repository: gitpodify/gitpodified-workspace-images

      - name: 🔧 Setup tools
        run: |
          sudo apt-get install python3-pip
          sudo pip3 install yq

      - name: 🔆 Install skopeo
        run: |
          . /etc/os-release
          # Update ca-certificates to avoid issues with letsencrypt SSL certificates
          sudo apt update && sudo apt --only-upgrade install ca-certificates -y
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
          sudo apt update && sudo apt install -y skopeo

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - name: Load environment variables as masked secrets
        uses: catchco/doppler-environment-loader@v1.0.2
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: ✍🏽 Authenicate against GHCR, Quay.io and Cloudsmith
        run: |
          echo "===> Authenicating against GHCR"
          sudo skopeo login -u RecapTimeBot --password=${{ secrets.GHCR_SERVICE_ACCOUNT_PASSWORD }} ${{env.GHCR_REGISTRY}}
          docker login -u RecapTimeBot --password=${{ secrets.GHCR_SERVICE_ACCOUNT_PASSWORD }} ${{env.GHCR_REGISTRY}}
          echo
          sleep 3

          echo "===> Authenicating against RHQCR"
          sudo skopeo login -u ${{ secrets.RHQCR_SERVICE_ACCOUNT_USERNAME }} --password=${{secrets.RHQCR_SERVICE_ACCOUNT_PASSWORD}} ${{env.RHQCR_REGISTRY}}
          docker login -u ${{ secrets.RHQCR_SERVICE_ACCOUNT_USERNAME }} --password=${{secrets.RHQCR_SERVICE_ACCOUNT_PASSWORD}} ${{env.RHQCR_REGISTRY}}

          echo "===> Authenticating against Cloudsmith"
          sudo skopeo login -u recaptimebot --password=${{secrets.CLOUDSMITH_API_KEY}} docker.cloudsmith.io
          docker login -u recaptimebot --password=${{secrets.CLOUDSMITH_API_KEY}} docker.cloudsmith.io

      - name: 🐳 Sync latest tag of images to Docker Hub
        run: |
          IMAGES=$(cat .github/promote-images.yml | yq '."ghcr.io/gitpodify/gitpodified-workspace-images/dazzle-build-artifact"."images-by-tag-regex"|keys[]' -r)
          for IMAGE in $IMAGES;
          do
            sudo skopeo copy \
            docker://${{ env.GHCR_REGISTRY }}/${{ env.GHCR_NAMESPACE }}/$IMAGE:latest \
            docker://${{ env.RHQCR_REGISTRY }}/${{ env.RHQCR_NAMESPACE }}/$IMAGE:latest

            sudo skopeo copy \
            docker://${{ env.GHCR_REGISTRY }}/${{ env.GHCR_NAMESPACE }}/$IMAGE:latest \
            docker://${{ env.CLOUDSMITH_REGISTRY }}/${{ env.CLOUDSMITH_NAMESPACE }}/$IMAGE:latest
          done
