.docker-lint:
    stage: lint
    script:
        # $CONTEXT_DOCKERFILE refers to path to Dockerfile within the $CONTEXT_DIR
        - ./.gitlab/ci/scripts/lint "$CONTEXT_DIR/${CONTEXT_DOCKERFILE:-"Dockerfile"}"
    variables:
      SKIP_IMAGE_CACHING: "true"

ws-base:lint:
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: base
    allow_failure: true
    #rules:
    #    - changes:
    #        - base/Dockerfile
    #        - "base/*-packages" # hint: base/install-packages and base/upgrade-packages

ws-full:lint:
    needs:
        - ws-base:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: full
    allow_failure: true
    #rules:
    #    - changes:
    #        - full/Dockerfile
    #        - full/*.sh

ws-vnc:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: vnc
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - vnc/Dockerfile
            - vnc/*.sh
ws-gecko:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
        - ws-vnc:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: gecko
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - gecko/Dockerfile

ws-mdbook:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: mdbook
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - mdbook/Dockerfile

ws-wasm:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: wasm
    allow_failure: true
    rules:
       - if: '$CI_PIPELINE_SOURCE == "schedule"'
       - changes:
           - .trigger-build
           - wasm/Dockerfile

ws-mongodb:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: mongodb
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - mongodb/Dockerfile

ws-postgres:lint:
   needs:
        - ws-base:lint
        - ws-full:lint
   extends:
       - .docker-lint
   variables:
      CONTEXT_DIR: postgres
   allow_failure: true
   rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - postgres/Dockerfile

ws-dart:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: dart
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - dart/Dockerfile

ws-flutter:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
        - ws-dart:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: flutter
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - flutter/Dockerfile

ws-dotnet:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: dotnet
    allow_failure: true
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
      - changes:
          - .trigger-build
          - dotnet/Dockerfile

ws-dotnet-vnc:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
        - ws-vnc:lint
        - ws-dotnet:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: dotnet
        CONTEXT_DOCKERFILE: vnc.Dockerfile
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - dotnet/vnc.Dockerfile

ws-dotnet-lts:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
        - ws-dotnet:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: dotnet/lts
        CONTEXT_DOCKERFILE: lts.Dockerfile
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - dotnet/lts.Dockerfile

ws-dotnet-lts-vnc:lint:
    needs:
        - ws-base:lint
        - ws-full:lint
        - ws-vnc:lint
        - ws-dotnet-lts:lint
    extends:
        - .docker-lint
    variables:
        CONTEXT_DIR: dotnet
        CONTEXT_DOCKERFILE: lts-vnc.Dockerfile
    allow_failure: true
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - .trigger-build
            - dotnet/lts-vnc.Dockerfile
