global:lint:
  stage: lint
  script:
    - |
      apk add py3-pip python3 shellcheck
      curl -sSL https://github.com/mvdan/sh/releases/download/v3.4.2/shfmt_v3.4.2_linux_amd64 -o shfmt
      mv shfmt /usr/local/bin/shfmt && sudo chmod +x /usr/local/bin/shfmt
      pip3 install pre-commit
    - pre-commit run --all-files
  allow_failure: true
