.docker-build-dazzle:
    stage: build
    script:
      - |
        echo "===== Debugging section ====="
        env | grep TAG_NAME
        env | grep CONTEXT
      - ./.gitlab/ci/scripts/wait-docker-tcp
      - ./.gitlab/ci/scripts/dazzle-build "$CONTEXT_DIR/$CONTEXT_DOCKERFILE" "$TAG_NAME"
    variables:
      BASE_TAG_NAME: quay.io/gitpodified-workspace-images/
      # Assume the defaults unless otherwise stated.
      CONTEXT_DOCKERFILE: Dockerfile
      # Needed for readiness checks via our script.
      DIND_RUN_HEALTHCHECK_BEFORE_BUILD: "true"

.docker-build-plain:
    extends:
      - .docker-build-dazzle
    stage: build
    script:
      - |
        echo "===== Debugging section ====="
        env | grep TAG_NAME
        env | grep CONTEXT
      - ./.gitlab/ci/scripts/wait-docker-tcp
      - set -x && bash ./.gitlab/ci/scripts/docker-build $CONTEXT_DIR/$CONTEXT_DOCKERFILE $TAG_NAME
    variables:
      BASE_TAG_NAME: quay.io/gitpodified-workspace-images
      # Assume the defaults unless otherwise stated.
      CONTEXT_DOCKERFILE: Dockerfile
      DIND_RUN_HEALTHCHECK_BEFORE_BUILD: "true"
      DEBUG: "true"

ws-base:build:
    needs:
      - ws-base:lint
    extends:
      - .docker-build-plain
    variables:
      TAG_NAME: $BASE_TAG_NAME/base
      CONTEXT_DIR: base
    rules:
      - if: '$CI_SELECTIVE_BUILD == "true"'
      - when: on_success

ws-full:build:
    needs:
      - ws-full:lint
      - ws-base:build
    extends:
      - .docker-build-plain
    variables:
      TAG_NAME: $BASE_TAG_NAME/full
      CONTEXT_DIR: full
    rules:
      - if: '$CI_TARGET_CONTEXT_DIR != "full" && $CI_SELECTIVE_BUILD == "true"'
        when: never
      - if: '$CI_TARGET_CONTEXT_DIR == "full" && $CI_SELECTIVE_BUILD == "true"'
      - changes:
          - .trigger-build
          - full/dockerfile
          - full/tests/*.yml
          - full/nginx/nginx.conf
          - full/apache2/apache2.conf
          - full/apache2/envvars
          - devkit/bin/gp-devenv
          - full/zshrc.d/*.zshrc
        when: on_success
      - when: manual
