.docker-build-dazzle:
    stage: build
    before_script:
        - ./.gitlab/ci/scripts/docker-cli-login
    script:
        - ./.gitlab/ci/scripts/dazzle-build "$CONTEXT_DIR/$CONTEXT_DOCKERFILE" "$TAG_NAME"
    variables:
      BASE_TAG_NAME: quay.io/gitpodified-workspace-images/

.docker-build-plain:
    extends:
      - .docker-build-dazzle
    stage: build
    script:
      - ./.gitlab/ci/scripts/docker-build "$CONTEXT_DIR/$CONTEXT_DOCKERFILE" "$TAG_NAME"
    variables:
      BASE_TAG_NAME: quay.io/gitpodified-workspace-images
      # Assume the defaults unless otherwise stated.
      CONTEXT_DOCKERFILE: Dockerfile

ws-full:build:
    needs:
      - ws-full:lint
    extends:
      - .docker-build-dazzle
    variables:
      TAG_NAME: $BASE_TAG_NAME/full
      CONTEXT_DIR: full
    rules:
      - changes:
          - full/dockerfile
          - full/tests/*.yml
          - full/nginx/nginx.conf
          - full/apache2/apache2.conf
          - full/apache2/envvars
